import { HOST_URL } from "constants/app.constant";
import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from "constants/navigation.constant";
import { NAV_LIST } from "./nav";

const navigationConfig = [
  {
    key: "home",
    path: "/home",
    title: "Target",
    translateKey: "nav.home",
    icon: "home",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "target",
    path: "/target",
    title: "Target",
    translateKey: "nav.target",
    icon: "home",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "schedule",
    path: "/schedule",
    title: "Jadwal",
    translateKey: "nav.schedule",
    icon: "home",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "monitoring",
    path: "/monitoring",
    title: "Monitoring",
    translateKey: "nav.monitoring",
    icon: "submission",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "monitoring.temperature",
        path: "/monitoring/temperature",
        title: "Suhu & Kelembapan",
        translateKey: "nav.monitoring.temperature",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "monitoring.generalSanitation",
        path: "/monitoring/general-sanitation",
        title: "Sanitasi Umum",
        translateKey: "nav.monitoring.generalSanitation",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "monitoring.productionSanitation",
        path: "/monitoring/production-sanitation",
        title: "Sanitasi Produksi",
        translateKey: "nav.monitoring.productionSanitation",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "monitoring.purchase",
        path: "/monitoring/purchase",
        title: "Pembelian",
        translateKey: "nav.monitoring.purchase",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "qualityAssurance",
    path: "/quality-assurance",
    title: "QA",
    translateKey: "nav.qualityAssurance",
    icon: "claim",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "qualityAssurance.extraction",
        path: "/quality-assurance/extraction",
        title: "Ekstraksi",
        translateKey: "nav.qualityAssurance.extraction",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityAssurance.finishedProduct",
        path: "/quality-assurance/finished-product",
        title: "Produk Jadi",
        translateKey: "nav.qualityAssurance.finishedProduct",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityAssurance.validation",
        path: "/quality-assurance/validation",
        title: "Validasi",
        translateKey: "nav.qualityAssurance.validation",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityAssurance.qualification",
        path: "/quality-assurance/qualification",
        title: "Kualifikasi",
        translateKey: "nav.qualityAssurance.qualification",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityAssurance.audit",
        path: "/quality-assurance/audit",
        title: "Audit",
        translateKey: "nav.qualityAssurance.audit",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "qualityControl",
    path: "/quality-control",
    title: "QC",
    translateKey: "nav.qualityControl",
    icon: "realization",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "qualityControl.sampling",
        path: "/quality-control/sampling",
        title: "Sampling",
        translateKey: "nav.qualityControl.sampling",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityControl.material",
        path: "/quality-control/material",
        title: "QC Material",
        translateKey: "nav.qualityControl.material",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityControl.bets",
        path: "/quality-control/bets",
        title: "QC Bets",
        translateKey: "nav.qualityControl.bets",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "qualityControl.sterilizationTryout",
        path: "/quality-control/sterilizationTryout",
        title: "Uji Sterilisasi",
        translateKey: "nav.qualityControl.sterilizationTryout",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "researchAndDevelopment",
    path: "/research-developement",
    title: "R&D",
    translateKey: "nav.researchAndDevelopment",
    icon: "claim",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "researchAndDevelopment.formulation",
        path: "/research-developement/formulation",
        title: "Formulasi",
        icon: "",
        translateKey: "nav.researchAndDevelopment.formulation",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "researchAndDevelopment.procedure",
        path: "/research-developement/procedure",
        title: "Prosedur",
        icon: "",
        translateKey: "nav.researchAndDevelopment.procedure",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "researchAndDevelopment.material",
        path: "/research-developement/material",
        title: "Material",
        icon: "",
        translateKey: "nav.researchAndDevelopment.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "maintenance",
    path: "/maintenance",
    title: "Pemeliharaan",
    translateKey: "nav.maintenance",
    icon: "mappingSales",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "maintenance.request",
        path: "/maintenance/request",
        title: "Permintaan",
        icon: "",
        translateKey: "nav.maintenance.request",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "maintenance.activity",
        path: "/maintenance/activity",
        title: "Aktifitas",
        icon: "",
        translateKey: "nav.maintenance.activity",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "pilotScaleBatch",
    path: "/pilot-scale-batch",
    title: "Pilot Scale Batch",
    translateKey: "nav.pilotScaleBatch",
    icon: "breakPelunasan",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "pilotScaleBatch.extraction",
        path: "/pilot-scale-batch/extraction",
        title: "Ekstraksi",
        icon: "",
        translateKey: "nav.pilotScaleBatch.extraction",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "pilotScaleBatch.processing",
        path: "/pilot-scale-batch/processing",
        title: "Pengolahan",
        icon: "",
        translateKey: "nav.pilotScaleBatch.processing",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "pilotScaleBatch.packing",
        path: "/pilot-scale-batch/packing",
        title: "Pengemasan",
        icon: "",
        translateKey: "nav.pilotScaleBatch.packing",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "production",
    path: "/production",
    title: "Produksi",
    translateKey: "nav.production",
    icon: "breakPelunasan",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "production.extraction",
        path: "/production/extraction",
        title: "Ekstraksi",
        icon: "",
        translateKey: "nav.production.extraction",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "production.processing",
        path: "/production/processing",
        title: "Pengolahan",
        icon: "",
        translateKey: "nav.production.processing",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "production.packing",
        path: "/production/packing",
        title: "Pengemasan",
        icon: "",
        translateKey: "nav.production.packing",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "production.stamp",
        path: "/production/stamp",
        title: "Stempel",
        icon: "",
        translateKey: "nav.production.stamp",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "production.deviation",
        path: "/production/deviation",
        title: "Penyimpangan",
        icon: "",
        translateKey: "nav.production.deviation",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "reception",
    path: "/reception",
    title: "Penerimaan",
    translateKey: "nav.reception",
    icon: "finance",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "reception.material",
        path: "/reception/material",
        title: "Material",
        icon: "",
        translateKey: "nav.reception.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "reception.nonMaterial",
        path: "/reception/non-material",
        title: "Non-Material",
        icon: "",
        translateKey: "nav.reception.nonMaterial",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "reception.extraction",
        path: "/reception/extraction",
        title: "Ekstraksi",
        icon: "",
        translateKey: "nav.reception.extraction",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "reception.finishedProduct",
        path: "/reception/finished-product",
        title: "Produk Jadi",
        icon: "",
        translateKey: "nav.reception.finishedProduct",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "expenditure",
    path: "/expenditure",
    title: "Pengeluaran",
    translateKey: "nav.expenditure",
    icon: "report",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "expenditure.material",
        path: "/expenditure/material",
        title: "Material",
        icon: "",
        translateKey: "nav.expenditure.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "expenditure.nonMaterial",
        path: "/expenditure/non-material",
        title: "Non-Material",
        icon: "",
        translateKey: "nav.expenditure.nonMaterial",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "expenditure.finishedProduct",
        path: "/expenditure/finished-product",
        title: "Produk Jadi",
        icon: "",
        translateKey: "nav.expenditure.finishedProduct",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "warehouse",
    path: "/warehouse",
    title: "Gudang",
    translateKey: "nav.warehouse",
    icon: "masterData",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "warehouse.storage",
        path: "/warehouse/storage",
        title: "Penyimpanan",
        icon: "",
        translateKey: "nav.warehouse.storage",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "warehouse.waste",
        path: "/warehouse/waste",
        title: "Limbah",
        icon: "",
        translateKey: "nav.warehouse.waste",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "warehouse.return",
        path: "/warehouse/return",
        title: "Pengembalian",
        icon: "",
        translateKey: "nav.warehouse.return",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "purchase",
    path: "/purchase",
    title: "Pembelian",
    translateKey: "nav.purchase",
    icon: "masterData",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "purchase.procurement",
        path: "/purchase/procurement",
        title: "Pengadaan",
        icon: "",
        translateKey: "nav.purchase.procurement",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "purchase.payment",
        path: "/purchase/payment",
        title: "Pembayaran",
        icon: "",
        translateKey: "nav.purchase.payment",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "purchase.request",
        path: "/purchase/request",
        title: "Permintaan",
        icon: "",
        translateKey: "nav.purchase.request",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "purchase.rndProduct",
        path: "/purchase/rndProduct",
        title: "Produk R&D",
        icon: "",
        translateKey: "nav.purchase.rndProduct",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "report",
    path: "/report",
    title: "Laporan",
    translateKey: "nav.report",
    icon: "masterData",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "report.formulasi",
        path: "/report/formulation",
        title: "Formulasi",
        icon: "",
        translateKey: "nav.report.formulasi",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "report.prosedur",
        path: "/report/procedure",
        title: "Prosedur",
        icon: "",
        translateKey: "nav.report.prosedur",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "report.material",
        path: "/report/material",
        title: "Material",
        icon: "",
        translateKey: "nav.report.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "document",
    path: "/document",
    title: "Dokumen",
    translateKey: "nav.document",
    icon: "masterData",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "document.formulasi",
        path: "/document/formulation",
        title: "Formulasi",
        icon: "",
        translateKey: "nav.document.formulasi",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "document.prosedur",
        path: "/document/procedure",
        title: "Prosedur",
        icon: "",
        translateKey: "nav.document.prosedur",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "document.material",
        path: "/document/material",
        title: "Material",
        icon: "",
        translateKey: "nav.document.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "waterSampling",
    path: "/water-sampling",
    title: "Sampling Air",
    translateKey: "nav.waterSampling",
    icon: "masterData",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "waterSampling.formulasi",
        path: "/water-sampling/formulation",
        title: "Formulasi",
        icon: "",
        translateKey: "nav.waterSampling.formulasi",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "waterSampling.prosedur",
        path: "/water-sampling/procedure",
        title: "Prosedur",
        icon: "",
        translateKey: "nav.waterSampling.prosedur",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "waterSampling.material",
        path: "/water-sampling/material",
        title: "Material",
        icon: "",
        translateKey: "nav.waterSampling.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "vendor-management",
    path: "",
    title: "Vendor Management",
    icon: "masterData",
    translateKey: "nav.vendor",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "vendor.list",
        path: "/vendor-management",
        title: "Vendor",
        icon: "",
        translateKey: "nav.vendor.material",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "base",
    path: "",
    title: "Master Data",
    icon: "masterData",
    translateKey: "nav.base",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "masterData.kategoriBarang",
        path: "/master-data/kategori-barang",
        title: "Kategori Barang",
        icon: "",
        translateKey: "nav.base.users",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "masterData.barangPurchase",
        path: "/master-data/barang-purchase",
        title: "Barang Purchase",
        icon: "",
        translateKey: "nav.base.users",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
];

export default navigationConfig;
