export const PageConfig = {
  moduleTitle: "Riset Bahan dan Vendor",
  pageTitle: "Riset Bahan dan Vendor",
  baseEnpoint: "research-development/riset-bahan-dan-vendor",
  pageCreate:
    "/research-development/trial-formulasi/riset-bahan-dan-vendor/add",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableExportTools: false,
  enableFilterTools: false,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "rnd_raw_material_details.raw_material.raw_material_code",
      label: "Kode Barang",
      sortable: true,
      width: "auto",
      is_show: true,
      type: "id",
    },
    {
      key: "raw_material_name",
      label: "Bahan",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "rnd_raw_material_details.raw_material.category",
      label: "Kategori",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "rnd_raw_material_details.material_status",
      label: "Status Bahan",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "rnd_raw_material_details.raw_material.stock",
      label: "Stok",
      sortable: false,
      width: "auto",
      is_show: true,
    },
  ],
};
