export const PageConfig = {
  moduleTitle: "Trial Bahan Kemas",
  pageTitle: "Trial Bahan Kemas",
  baseEnpoint: "purchase/pembayaran",
  pageCreate: "/research-development/trial-formulasi/trial-bahan-kemas/add",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableExportTools: false,
  enableFilterTools: false,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "trial_name",
      label: "Nama Trial",
      sortable: true,
      width: "auto",
      is_show: true,
      type: "id",
    },
    {
      key: "trial_date",
      label: "Tanggal Pelaksanaan",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "procedure",
      label: "Prosedur",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "status",
      label: "Status",
      sortable: false,
      width: "auto",
      is_show: true,
    },
  ],
};
