export const PageConfig = {
  moduleTitle: "Pembayaran",
  pageTitle: "Pembayaran",
  baseEnpoint: "purchase/pembayaran",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: true,
  enableFilterTools: true,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "payment_id",
      label: "Id",
      sortable: true,
      width: "auto",
      is_show: true,
      type: "id",
    },
    {
      key: "po_id",
      label: "Id Po",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "po_name",
      label: "Name PO",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "vendor_name",
      label: "Vendor",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "amount",
      label: "Jumlah Pengeluaran",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "category",
      label: "Kategori",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "payment_method",
      label: "Metode Pembayaran",
      sortable: false,
      width: "auto",
      is_show: true,
    },

    {
      key: "payment_date",
      label: "Tanggal Pengajuan",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "status",
      label: "Status",
      sortable: true,
      width: "auto",
      is_show: true,
      type: "status",
      // sticky: "right",
    },
  ],
};
